sudo: enabled
language: python
python:
  - "3.6"

before_install: 
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose 
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose build

script: 
  - docker-compose up -d
  - sleep 10
  - docker-compose run worker coverage run -m unittest resources/testsYotube.py resources/testsTwitch.py resources/testsSteam.py resources/testsImporter.py
  - docker-compose run worker coverage report
  - mv worker/.coverage .

after_success:
  - docker-compose run -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN -w /queue worker coveralls

deploy:
  - provider: heroku
    api_key:
      secure: ${HEROKU_KEY}
    app: gbi-importadores2-staging
    on:
      repo: fga-eps-mds/2018.2-GamesBI_Importadores
      branch: develop

  - provider: heroku
    api_key:
      secure: ${HEROKU_KEY}
    app: gbi-importadores2-production
    on:
      repo: fga-eps-mds/2018.2-GamesBI_Importadores
      branch: master
