version: '3.5'

services:
  import:
    build: .
    volumes:
      - ./webapp:/opt/webapp
    ports:
      - "5000:5000"
    networks:
      - proxynet
    env_file:
      - .env
  worker:
    build:
      context: worker
      dockerfile: Dockerfile
    networks:
      - proxynet
    depends_on:
      - redis
  redis:
    image: redis
    networks:
      - proxynet

networks:
  proxynet:
    name: GamesBI-network
