version: '3.5'

services:
  worker:
    build:
      context: worker
      dockerfile: Dockerfile
    networks:
      - proxynet
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./worker:/queue
  redis:
    image: redis
    networks:
      - proxynet

networks:
  proxynet:
    name: GamesBI-network
