version: '3.5'

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - proxynet
    depends_on:
      - redis
    environment:
      - COVERALLS_REPO_TOKEN
    env_file:
      - .env
    volumes:
      - .:/queue
  redis:
    image: redis
    networks:
      - proxynet

networks:
  proxynet:
    name: GamesBI-network
