version: '3.5'

services:
  import:
    build: .
    volumes:
      - ./webapp:/opt/webapp
    ports:
      - "5000:5000"
    networks:
      - proxynet
    env_file:
      - .env

networks:
  proxynet:
    name: GamesBI-network
